name: Update Jenkins Plugins

on:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Get latest jenkins-plugin-manager version
        id: get_version
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/jenkinsci/plugin-installation-manager-tool/releases/latest \
            | grep 'browser_download_url' \
            | grep 'jenkins-plugin-manager-[0-9.]*\.jar"' \
            | grep -v '\.sha256' \
            | head -n 1 \
            | cut -d '"' -f 4)
          echo "LATEST_URL=$LATEST_URL" >> $GITHUB_ENV

      - name: Download jenkins-plugin-manager jar
        run: |
          curl -L -o jenkins-plugin-cli.jar "$LATEST_URL"

      - name: Update plugins.txt
        run: |
          java -jar jenkins-plugin-cli.jar \
             --plugin-file files/plugins.txt \
             --available-updates \
             --output txt > updated-plugins.txt
          if [ -s updated-plugins.txt ]; then
             mv updated-plugins.txt files/plugins.txt
             echo "plugins.txt updated with new plugin versions."
          else
             echo "No plugin updates available; plugins.txt left unchanged."
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-jenkins-plugins
          title: "Update Jenkins Plugins"
          body: |
            This PR updates Jenkins plugins in files/plugins.txt to their latest versions.